In [ ]:
data=1

print(data)

1


In [3]:
data="abcd "
print(data)

abcd 


In [ ]:
marks1=90
marks2=80
marks3=70
marks4=60
marks5=50
marks6=40

In [4]:
#list

marks=[] #empty list

print(marks)

[]


In [5]:
marks=[90,80,70,60,50,40] #list with values


print(marks)

[90, 80, 70, 60, 50, 40]


In [8]:
print(marks[0]) #accessing first element
print(marks[1]) #accessing second element
print(marks[4])

print(marks[5]) #accessing last element

90
80
50
40


In [9]:
marks=[90,80,70,60,50,40] 


print(marks[-1]) #accessing last element using negative index (circular indexing)

40


In [10]:
names=["nirmal","nithin","nithya","nishad","nisha"]

print(len(names))

5


In [13]:
#add elements to the list
data=[]

data.append(10)
print(data)


data.append(20)
print(data)

data.append(30)
print(data)



[10]
[10, 20]
[10, 20, 30]


In [20]:
a=[1,2,3,4,5]

a.append(6)
a.append(7)

print(a)

[1, 2, 3, 4, 5, 6, 7]


In [ ]:
#remove elements from the list
#lists uses the LIFO (Last In First Out) principle
x=[1,2,3,4,5,6,7,8,9,10]
print(x)


x.pop()
print(x)

x.pop() 
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8]


In [23]:
names=["tom","jerry","spike","tyke"]
print(names)


#remove spike
names.remove("spike")
print(names)


#remove jerry
names.pop(1)
print(names)

['tom', 'jerry', 'spike', 'tyke']
['tom', 'jerry', 'tyke']
['tom', 'tyke']


In [25]:
name="nirmal"

print(name)
#delet name from memory

del name

print(name) #this will give an error because name is deleted from memory

nirmal


NameError: name 'name' is not defined

In [ ]:
#update elements in the list
names=["Bob","Alice","Charlie","David"]

names[2]="Charlie Chaplin"
print(names)


['Bob', 'Alice', 'Charlie Chaplin', 'David']


In [ ]:
marks=[10,20,30,40,50,60]

print(marks[0:2]) # get first 2 elements of the list (0,1)

print(marks[0:3]) #get first 3 elements of the list (0,1,2)


print(marks[3:6]) #get elements from index 3 to 5 (3,4,5)

[10, 20]
[10, 20, 30]
[40, 50, 60]


In [32]:
print(marks[3:])

[40, 50, 60]


In [31]:
print(marks[-3:])

[40, 50, 60]


In [34]:
grocery_list=["milk","bread","eggs","butter","cheese","yogurt"]

print(grocery_list)


for item in grocery_list:
    print(item)

['milk', 'bread', 'eggs', 'butter', 'cheese', 'yogurt']
milk
bread
eggs
butter
cheese
yogurt


In [35]:
for item in grocery_list:
    print(f'Grocery item: {item}')

Grocery item: milk
Grocery item: bread
Grocery item: eggs
Grocery item: butter
Grocery item: cheese
Grocery item: yogurt


In [37]:
i=0
for item in grocery_list:
    print(f'Grocery item {i+1}: {item}')
    i+=1

Grocery item 1: milk
Grocery item 2: bread
Grocery item 3: eggs
Grocery item 4: butter
Grocery item 5: cheese
Grocery item 6: yogurt


In [39]:
for i,item in enumerate(grocery_list):
    print(f'{i+1}: {item}')



1: milk
2: bread
3: eggs
4: butter
5: cheese
6: yogurt


In [46]:
marks=[89,53,26,92,23,13,64]
print(marks)

#sort the list

marks.sort()  # sort in ascending order
print(marks)


marks.sort(reverse=True) 
print(marks)  # sort in descending order


[89, 53, 26, 92, 23, 13, 64]
[13, 23, 26, 53, 64, 89, 92]
[92, 89, 64, 53, 26, 23, 13]


In [42]:
marks=[89,53,26,92,23,13,64]


print(sorted(marks)) #sorted function returns a new sorted list

[13, 23, 26, 53, 64, 89, 92]


In [ ]:
names=["Bob","Alice","Charlie","Zavid",'alice'] 

print(sorted(names)) #sorted function returns a new sorted list of strings in alphabetical order

['Alice', 'Bob', 'Charlie', 'Zavid', 'alice']


In [49]:
grocery_list=["milk","bread","eggs","butter","cheese","yogurt"]


#find index of butter

print(grocery_list.index("butter")) #returns the index of the first occurrence of the item

3


In [50]:
marks=[10,20,30,40,50,60,70,80,90,100]

#calculate average of marks

total=0
for mark in marks:
    total+=mark

average=total/len(marks)
print(f'Average marks: {average}')  # print the average marks

Average marks: 55.0


In [ ]:
marks=[10,20,30,40,50,60,70,80,90,100]

import statistics

print(statistics.mean(marks))  # calculate mean of marks using math module


print(sum(marks)/len(marks))

55.0


In [61]:
marks=[10,20,30,40,50,60,70,80,90,100]


print(sum(marks))
print(min(marks))  # find minimum value in the list
print(max(marks))  # find maximum value in the list

550
10
100


In [ ]:
student_details=['Tom',30,'Rodirgues',False] #dynamic list with different data types

print(student_details)

['Tom', 30, 'Rodirgues', False]


In [64]:
# multi dimensional list

marks=[[1,2,3],[4,5,6],[7,8,9]]

print(marks)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [4]:
import numpy as np
marks=[[1,2,3],[4,5,6],[7,8,9]]
x=np.array(marks)

print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
marks=[[1,2,3],[4,5,6],[7,8,9]]


print(marks[1][1])


for i in marks:
    for j in i:
        print(j)

5
1
2
3
4
5
6
7
8
9
